name: Deploy Dotfiles

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync dotfiles to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY_AVI }}
        script: |
          rsync -avz --delete ./ root@${{ secrets.REMOTE_HOST }}:~/dotfiles/
          ssh user@${{ secrets.REMOTE_HOST }} 'cd ~/dotfiles && stow bash && stow vim && stow git'
