name: Deploy Dotfiles

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_AVI }}

    - name: Sync dotfiles to remote server
      run: |
        rsync -avz --delete ~/dotfiles/ user@remote-server:~/dotfiles/
        ssh root@64.227.138.56 'cd ~/dotfiles && stow bash && stow vim && stow git'
