name: Deploy Dotfiles

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY_AVI }}
        port: 22
        script: la
      #   script: |
      #     rsync -avz --delete ./ root@${{ secrets.REMOTE_HOST }}:~/dotfiles/
      #     ssh user@${{ secrets.REMOTE_HOST }} 'cd ~/dotfiles && stow bash && stow vim && stow git'
